collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8422939
color:
  saturation: 0.3960573
  brandStrength: 0.7903226
  lightness: 0.7275985
  brandColors:
    - '#FFFFFF'
    - '#79848A'
    - '#D42E3C'
    - '#0F0F0D'
    - '#454640'
  rhythmicContrast: 0.2007169
layout_spectrum: 1
name: NEKTARSTOCK
